# SPDX-License-Identifier: (GPL-2.0 OR BSD-2-Clause)

include ../Makefile

# XDP_TARGETS := ./programs/attached/events/sched_switch.bpf
# XDP_FUNCTION := ____sched_switch

XDP_TARGETS := ./programs/attached/dispatchers/syscall_exit.bpf
XDP_FUNCTION := ____sys_exit